### ISSUE TITLE
change app opens sidebar

### ISSUE THREAD

**Issue by Tealk** [hjiangsu/thunder#122] opened 2023-06-27 17:27 UTC
**Description**  
The swipe gesture to switch the app opens the sidebar This is a little annoying when returning to the app It would be nice if you could exclude the lower area which is for the app control

**How to Reproduce**  
1) Open app
2) Switch the app with the swipe gesture
3) return to the app

**Device & App Version:**  
 - Device: Pixel6
 - OS: GraphenOS13
 - Version 0.2.1+8

**Comment by CTalvio** [comment] 2023-06-29 01:19
I have recorded a video demonstrating this issue. The side menu gesture is recognized, even when interacting with the gesture bar/navbar in android.

https://github.com/hjiangsu/thunder/assets/4365015/94b1d0cc-07d4-4490-9fa6-1e084bb58f43

**Comment by hjiangsu** [comment] 2023-06-29 02:06
Oh, hmm. I'll have to think about how to fix this since theres no easy fix I can immediately think of.

I could add in a setting which enables/disables this gesture that'll default to off unless you toggle it on.

It'll be hard to get only the swipe gesture to work on the top half of the navigation bar since the whole gesture is detected inside of that bottom nav bar

**Comment by machinaeZER0** [comment] 2023-06-30 13:52
What if the side panel gesture only triggered when you swiped right on the Home icon? Right now that consistently works for me without triggering any OS shenanigans, and it seems like the side panel can only trigger when Thunder's nav bar is displayed anyway?

**Comment by CTalvio** [comment] 2023-06-30 15:43
> What if the side panel gesture only triggered when you swiped right on the Home icon/the nav bar icons in general? Right now that consistently works for me without triggering any OS shenanigans, and it seems like the side panel can only trigger when Thunder's nav bar is displayed anyway?

How exactly would this resolve the gesture conflict for people using the gesture bar?

**Comment by machinaeZER0** [comment] 2023-06-30 15:49
Right now the sidebar gesture detection extends to the bottom of my screen, which is the problem - it overlaps with the area where OS gestures get triggered. If the Thunder gesture changes so that the area below the actual icons in its nav bar is a "dead zone" for app interaction, then I think that would make a huge difference. Testing on Android right now, and swiping across the nav bar icons opens the side panel without activating the OS app switcher.

Are we saying the same thing?

**Comment by CTalvio** [comment] 2023-06-30 18:42
> Right now the sidebar gesture detection extends to the bottom of my screen, which is the problem - it overlaps with the area where OS gestures get triggered. If the Thunder gesture changes so that the area below the actual icons in its nav bar is a "dead zone" for app interaction, then I think that would make a huge difference. Testing on Android right now, and swiping across the nav bar icons opens the side panel without activating the OS app switcher.
> 
> Are we saying the same thing?

We are clearly talking about different things. The problem is with the gesture bar, not the navbar. Because the gesture for opening the side menu is the SAME as the one for changing apps. WHEN USING GESTURES, which your talking about icons suggests you are not.

I demonstrate this, in the video I posted, did you see it?

![image](https://github.com/hjiangsu/thunder/assets/4365015/a0701a4f-74f4-42bf-ad03-af7a997f1de6)

**Comment by CTalvio** [comment] 2023-06-30 18:46
> Right now the sidebar gesture detection extends to the bottom of my screen, which is the problem - it overlaps with the area where OS gestures get triggered. If the Thunder gesture changes so that the area below the actual icons in its nav bar is a "dead zone" for app interaction, then I think that would make a huge difference. Testing on Android right now, and swiping across the nav bar icons opens the side panel without activating the OS app switcher.
> 
> Are we saying the same thing?

Ah. You are suggesting the gesture should only work when swiping the APP navbar. The HOME navbar should be a dead-zone. You are mixing terms.

It only working when swiping the APP navbar should be obvious, that was the intention from the start, I think.

**Comment by machinaeZER0** [comment] 2023-06-30 22:12
No reason to be weird about it, just trying to be helpful :)

**Comment by bactaholic** [comment] 2023-07-02 01:53
hey all, working on this issue now. I've currently taken @hjiangsu idea of just making it a toggle-able option in the settings as this was frustrating me as well, but I still wanted a way to access the sidebar without reaching up, so I added a double tap function to the navbar as well.

Both options can be used simultaneously, you can select one or the other, or turn both off entirely if that is your preference. I have to clean up what I wrote a bit and I'll be making a pull request soon, hopefully its sufficient to fix this issue.

**Comment by hjiangsu** [comment] 2023-07-02 05:38
Thanks so much for contributing! I'll attach this here since it relates to this issue: #165

**Comment by hjiangsu** [comment] 2023-07-04 06:14
A pre-release version v0.2.1-alpha.1+11 has been added to toggle on/off the swipe gestures! Feel free to test it out and provide feedback if needed.

For the double-tap gesture, its currently disabled so that I can do some more tests/changes to allow the bottom nav bar to still be responsive even with the double-tap gesture implemented in

**Comment by hjiangsu** [comment] 2023-07-09 16:23
Closing as its been released in v0.2.1+11!

**Closed by hjiangsu** 2023-07-09 16:23 UTC
Labels: bug, fixed in upcoming release
