### ISSUE TITLE
App switches back to post list after commenting

### ISSUE THREAD

**Issue by rjwolke** [hjiangsu/thunder#218] opened 2023-07-04 09:42 UTC
**Description**  
After writing a comment, the app exits the post view automatically instead of showing the post that I just commented on.

**How to Reproduce**  
1. Go to 'Post view'
2. Write Comment
3. Click Send

**Expected Behavior**  
Display the comment that was just written.

**Device & App Version:**  
 - Device: Google Pixel 4A
 - OS: Android 13
 - Version v0.2.1+10 (via FDroid/IzzyOnDroid)

**Comment by hjiangsu** [comment] 2023-07-04 13:10
Could you let me know in what cases this happen so that I can track it down a bit better?

- Does replying to the post cause this to occur?
- Does replying to a comment cause this to occur?
- Does editing your comment cause this to occur?

Those three things will help me get a better understanding on the issue!

**Comment by CTalvio** [comment] 2023-07-04 18:11
Confirmed to happen when replying to post.

**Comment by guigs4** [comment] 2023-07-05 13:20
I had a similar issue when implementing #126. 
It was caused by 
Navigator.of(context).pop().

Please be aware that the develop branch seems different from main (changed to “Navigator.pop(context)” in create_comment_modal.dart ).

Apologies for not being able to check it properly right now, but I wanted to give y’all a lead.

**Comment by hjiangsu** [comment] 2023-07-05 13:28
This is a known issue and should be fixed already, but not yet released yet in the upcoming nightly version!

**Comment by hjiangsu** [comment] 2023-07-09 16:35
Closing this issue since it has been released in v0.2.1+11!

**Closed by hjiangsu** 2023-07-09 16:35 UTC
Labels: bug, fixed in upcoming release
