### ISSUE TITLE
Can't collapse comments

### ISSUE THREAD

**Issue by krestenlaust** [hjiangsu/thunder#133] opened 2023-06-28 15:10 UTC
**Is your feature request related to a problem? Please describe.**
In previous versions, collapsing a comment meant collapsing it. Now it only collapse child comments, stilling taken up space. 

**Describe the solution you'd like**
Want it back the way it was. Only collapsing child comments is non-standard and illogical behavior.

Pressing on a comment should also collapse it, not just child comments. I'm done reading it, I don't need it to take up my screen.

This is also default behavior on public link aggregator reddit, and other lemmy apps.

I'm using the latest release as of writing.

**Comment by hjiangsu** [comment] 2023-06-28 15:45
This is a duplicate of #119 - I'll close this issue and updates will be kept in #119

**Closed by hjiangsu** 2023-06-28 15:45 UTC
Labels: enhancement

**Comment by krestenlaust** [comment] 2023-06-29 05:47
Sorry, forgot to look for duplicates
