### ISSUE TITLE
Duplicate posts while scrolling

### ISSUE THREAD

**Issue by bokeTanuki** [hjiangsu/thunder#129] opened 2023-06-28 05:44 UTC
**Description**  
Some of the posts are duplicates or duplicated in the feed.

**How to Reproduce**  
1. Go to Thunder app Local posts.
2. Click on Sort by New.
3. Scroll down to view posts. 
4. You can see some of the posts are duplicated. 

**Expected Behavior**  
Posts should not be duplicated.

**Screenshots**  
![Screenshot_20230628-110031](https://github.com/hjiangsu/thunder/assets/122195435/a81f3821-0fe8-4de2-bf67-80a9912bbd7c)

**Device & App Version:**  
 - Device: Pixel 6a
 - OS: Android 13
 - Version 0.2.1+8

**Additional Context**

**Comment by Poolitzer** [comment] 2023-07-02 06:54
This is a duplicate of #103

**Comment by hjiangsu** [comment] 2023-07-02 06:56
I'll close this as it is a duplicate issue - follow the other issue for updates on this!

**Closed by hjiangsu** 2023-07-02 06:56 UTC
Labels: bug
