### ISSUE TITLE
Setting to have thumbnails on the right

### ISSUE THREAD

**Issue by CTalvio** [hjiangsu/thunder#89] opened 2023-06-25 21:54 UTC
I would like to be able to set the the post thumnails to be on the right. As I am right handed, scrolling using one hand and opening the image previews one handed would become easier.

**Comment by realeatham** [comment] 2023-06-25 22:05
That should be a new post view mode

**Comment by machinaeZER0** [comment] 2023-06-26 02:22
I made an issue for this earlier today, if we're both talking about compact mode! #78

**Comment by hjiangsu** [comment] 2023-06-26 07:06
I'll close this as this is a duplicate of #78

**Closed by hjiangsu** 2023-06-26 07:06 UTC
Labels: duplicate, enhancement
