### ISSUE TITLE
Option to fully collapse tapped comment

### ISSUE THREAD

**Issue by thomasgirgenti** [hjiangsu/thunder#118] opened 2023-06-27 17:07 UTC
**Is your feature request related to a problem? Please describe.**

From the `v0.2.1+8` release notes:
> Tapping on a comment will now only collapse/hide the replies, and not the comment itself - contribution from @vbh

I really liked the old behavior (collapse the tapped comment & hide its children).

**Describe the solution you'd like**
Add a setting that allows users to select between one of two behaviors when tapping a comment:
1. Only collapse/hide the replies, and not the comment itself
2. Hide replies and collapse the comment itself

**Describe alternatives you've considered**
Living w/ the new behavior.

**Additional context**
PR in which this behavior was changed for release 0.2.1+8: https://github.com/hjiangsu/thunder/pull/95

**Comment by tunglith** [comment] 2023-06-27 17:11
@hjiangsu Can we merge this one with mine ?

**Comment by hjiangsu** [comment] 2023-06-28 17:03
I'll close this since its a duplicate of #119

**Closed by hjiangsu** 2023-06-28 17:03 UTC
