### ISSUE TITLE
Nav bar swipe to open side panel triggers accidentally

### ISSUE THREAD

**Issue by machinaeZER0** [hjiangsu/thunder#150] opened 2023-06-30 03:59 UTC
**Description**  
On modern Android phones, you can hold and"push up" from the bottom of the screen to engage app switching, and you can swipe between apps by swiping right at the very bottom of the screen. I've found that this behavior (particularly the latter behavior) frequently triggers the new behavior of swiping across the Thunder nav bar, and thus opens the app's side panel.

This is a very small and silly thing, but if it were possible to perhaps add some "dead zone" at the bottom of the nav bar, that might prevent accidental pane-opening during these multitasking gestures? It can sometimes get in the way of taking app screenshots, and is otherwise just a small quirk. Not urgent by any means!

**Device & App Version:**  
This is happening for me on my Pixel 4a, but potentially this could be happening for other Android users who use the modern Android swipe navigation (and possibly iPhone users?)

**Comment by hjiangsu** [comment] 2023-06-30 06:43
This is a duplicate of #122. I'll close this issue, and further discussions can take place in that issue, thanks!

**Closed by hjiangsu** 2023-06-30 06:43 UTC
Labels: bug

**Comment by machinaeZER0** [comment] 2023-06-30 13:48
Ack, sorry - I tried to see if there was an existing ticket and I missed this somehow!
