### ISSUE TITLE
Timeout when upvoting comment

### ISSUE THREAD

**Issue by any1th3r3** [hjiangsu/thunder#88] opened 2023-06-25 20:53 UTC
**Description**  
Timeout when upvoting a comment (or post itself) from within a thread. This seems to be specific to my beehaw account so far (I couldn't reproduce the issue with my lemmy.ca account, even within the exact same threads / upvoting the same comments).

**How to Reproduce**  
1. Click on post.
2. Attempt to upvote comment or the post itself
3. See timeout error
4. The comment or post will actually be upvoted, but it won't be shown

**Expected Behavior**  
No error message. I would expect the timeout to be consistent with what is applied in the home feed (I've noticed it usually takes around 8s to upvote a post with my beehaw account? While the timeout seems to be 5s from within a post itself) 

**Screenshots**  
![Screenshot_20230625-134106](https://github.com/hjiangsu/thunder/assets/9209426/3ad6fa57-d3d2-40b7-8ba1-614e29de83be)

**Device & App Version:**  
 - Device: Pixel 6 Pro
 - OS: GrapheneOS
 - Version Android 13

**Comment by machinaeZER0** [comment] 2023-06-26 02:30
Semi-related, but I was curious if the time it takes for a vote to actually display was itself a bug? I guess I'm used to that being visually instantaneous in other apps, but it may be that those apps update the vote count immediately on our end while the information is still being sent out? If that were possible it would be cool to implement I think, in addition to exploring this timeout behavior!

**Comment by machinaeZER0** [comment] 2023-06-26 11:32
That all makes sense to me, thanks for taking the time to explain!😄

**Comment by any1th3r3** [comment] 2023-06-26 21:36
> Unfortunately, this is really dependent on the instance that you're on and how much load that instance is handling - the timeout errors occur when the server(instance) takes too long to respond back with the updated data.
  
Yeah, that's completely fair! I know that we (beehaw users) tend to have timeout issues pretty often (even on desktop), so I'm not too surprised this would arise with mobile apps as well.  
I was mostly surprised to see discrepancies in the behaviour between upvotes on the home feed and in a post.

**Comment by machinaeZER0** [comment] 2023-06-27 18:30
@hjiangsu would it be helpful to make a ticket for the up/downvote delay, or is it fine being encapsulated within this timeout ticket?

**Comment by hjiangsu** [comment] 2023-07-02 06:52
I will close this as I think the issue is generally with the instance and not from Thunder itself, but feel free to open up another issue if you think otherwise!

**Closed by hjiangsu** 2023-07-02 06:52 UTC
Labels: bug
