### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by deepu2** [hjiangsu/thunder#4] opened 2023-06-17 03:47 UTC
**Describe the bug**
Cannot login to instance https://lemmy.fmhy.ml

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10 Pro
 - OS: Android 13
 - Version 0.1.1 alpha

**Additional context**
Tried changing the default instance but that doesn't seem to be working as well.

Keeps throwing username not found error.

**Comment by realeatham** [comment] 2023-06-17 03:53
Can you login to the web version

**Comment by armandojrod** [comment] 2023-06-17 03:57
Cannot login to instance lemmy.world  
![image](https://github.com/hjiangsu/thunder/assets/10835960/d430bae6-1e0c-4929-a05a-ac676bff1a56)

**Comment by realeatham** [comment] 2023-06-17 03:59
@armandojrod that was fixed in 0.1.1. update

**Comment by armandojrod** [comment] 2023-06-17 04:04
> @armandojrod that was fixed in 0.1.1. update

Yes, just saw the update. I was first installing through Fdroid

**Comment by hjiangsu** [comment] 2023-06-17 04:04
Hmm, the only instances i have tested so far is lemmy.world and lemmy.ml (only signed up for those instances). Although it should technically work with other instances, there _may_ be slight differences

**Comment by hjiangsu** [comment] 2023-06-17 04:10
@deepu2 Could you try to re-install the app, and login again without modifying the default instance setting? For the instance url, try to use `lemmy.fmhy.ml` and omit the `https://` if you haven't already!

The default instance setting was left there accidentally, and was a in-development feature that snuck into the release

**Comment by deepu2** [comment] 2023-06-17 04:41
@hjiangsu I've reinstalled and tried to login without changing settings, same error. ![Screenshot_2023-06-17-14-40-55-190_com.hjiangsu.thunder.jpg](https://github.com/hjiangsu/thunder/assets/30926681/6bbf3e10-1ab9-4f7a-baf0-0c88cc3ca543)

**Comment by BapRx** [comment] 2023-06-17 07:11
I tried to signup on this fmhy instance but it would always timeout, it's probably related to your issues. I logged in on another instance without issues.

**Comment by dantoms** [comment] 2023-06-17 16:22
I cannot sign in on the lemmy.ml instance either

**Comment by TRiggAtGM** [comment] 2023-06-19 13:31
I'm having this same experience for both beehaw and itjust.works

I'm using the FDroid version

**Comment by realeatham** [comment] 2023-06-19 20:56
Don't use the f droid version
It's out of date

**Comment by hjiangsu** [comment] 2023-06-22 21:49
For those who are still having login issues, I have created a new discussion page to talk about any recurring issues on this topic! Using the discussion will help me organize better what particular instances are having issues, the particular versions affected, and hopefully allow me to track down the root cause.

I'll close this issue for now. Please use this discussion page for future/recurrent login issues: https://github.com/hjiangsu/thunder/discussions/41

**Closed by hjiangsu** 2023-06-22 21:49 UTC
