### ISSUE TITLE
after comment on main page

### ISSUE THREAD

**Issue by Tealk** [hjiangsu/thunder#229] opened 2023-07-05 07:33 UTC
**Description**  
When I post a comment, I am thrown back to the posts overview instead of seeing the post I commented on.

**How to Reproduce**  
1. Open a Post
2. Click on comment
3. Send comment

**Expected Behavior**  
That I see the post

**Device & App Version:**  
 - Device: Pixel6
 - OS: GraphenOS 13
 - Version 2.0.1-alpha.1+11

**Comment by hjiangsu** [comment] 2023-07-05 14:14
This is a duplicate of #218 - I'll close this issue but refer to that ticket for more context

**Closed** 2023-07-05 14:14 UTC
Labels: bug
